// <auto-generated />
namespace WSafe.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RefinarRiesgo7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefinarRiesgo7));
        
        string IMigrationMetadata.Id
        {
            get { return "202112141946560_RefinarRiesgo7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
