// <auto-generated />
namespace WSafe.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MejoraIncidentes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MejoraIncidentes));
        
        string IMigrationMetadata.Id
        {
            get { return "202201061831073_MejoraIncidentes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
