// <auto-generated />
namespace WSafe.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IndicatorsImplementation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndicatorsImplementation));
        
        string IMigrationMetadata.Id
        {
            get { return "202201110027164_IndicatorsImplementation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
