// <auto-generated />
namespace WSafe.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IndicatorsImplementation111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndicatorsImplementation111));
        
        string IMigrationMetadata.Id
        {
            get { return "202201112353355_IndicatorsImplementation111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
