// <auto-generated />
namespace WSafe.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateCapacitationVM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateCapacitationVM));
        
        string IMigrationMetadata.Id
        {
            get { return "202404241738068_updateCapacitationVM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
